yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
# from django.views.decorators.cache import cache_page

app_name = 'space_posts'

urlpatterns = [
    # path('', cache(60)(views.index), name='posts'),
    path('', views.index, name='posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from yatube import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='space_posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
{% if 'author' in request.path_info or 'tech' in request.path_info %}
<style type="text/css">
  body {
      background: #fc0;
  }
</style>
{% endif %}
        <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'space_posts:posts' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class= "nav-link {% if view_name  == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'space_posts:post_create' %}active{% endif %}"
              href="{% url 'space_posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:password_change_form' %}active{% endif %} link-light"
              href="{% url 'users:password_change_form' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %} link-light"
             href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li class="nav-item">
            <a
                    class="nav-link {% if view_name  == 'space_posts:profile' %}active{% endif %}  link-light"
              href="{% url 'space_posts:profile' user.username %}"
            >
              Пользователь: {{ user.username }}
            </a>
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}  link-light"
              href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %} link-light"
              href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>       
</header>

yatube/templates/includes/paginator.html
<div>
    {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation" class="my-5">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Предыдущая
                </a>
            </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item active">
                    <span class="page-link">{{ i }}</span>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Следующая
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                Последняя
                </a>
            </li>
            {% endif %}    
        </ul>
        </nav>
    {% endif %}
</div>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'space_posts:posts' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'space_posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}