yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
# from django.views.decorators.cache import cache_page

app_name = 'space_posts'

urlpatterns = [
    # path('', cache(60)(views.index), name='posts'),
    path('', views.index, name='posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from yatube import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='space_posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
# from tabnanny import verbose
from django.urls import reverse
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Подпишите свой опус'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Опеределите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Посты пользователей'
        verbose_name_plural = 'Посты пользователей'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse('space_posts:post_detail', kwargs={'post_id': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Ваш комментарий',

    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self):
        return f'{self.user}-->{self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment
from django.utils.translation import ugettext_lazy as _
# from django.core.exceptions import ValidationError
# from captcha.fields import CaptchaField


class PostForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст'),
            'group': _('Группа'),
        }

    # def clean_text(self):
    #     text = self.cleaned_data['text']
    #     if len(text) < 10:
    #         raise ValidationError(
    #           'Такие маленькие посты на этом сайте недопустимы'
    #         )

    #     return text


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': _('Комментарий'),
        }

yatube/posts/views.py
from .models import Post, Group, User, Follow
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

N_EXEMPLE: int = 10


def index(request):
    post_list = Post.objects.all().select_related('author', 'group')
    paginator = Paginator(post_list, N_EXEMPLE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'index': True
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author', 'group')
    paginator = Paginator(posts, N_EXEMPLE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(
        author=author).select_related('author', 'group')
    number_posts = posts.count()
    paginator = Paginator(posts, N_EXEMPLE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = (Follow.objects.filter(user=request.user).filter(
            author=author).exists())
    user_is_author = request.user == author
    context = {
        'username': username,
        'number_posts': number_posts,
        'page_obj': page_obj,
        'author': author,
        'following': following,
        'user_is_author': user_is_author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    user_request = request.user
    post = get_object_or_404(Post, id=post_id)
    posts = Post.objects.filter(author=post.author)
    number_posts = posts.count()
    can_edit = user_request == post.author
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'number_posts': number_posts,
        'post_id': post_id,
        'can_edit': can_edit,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        user = request.user
        post = form.save(commit=False)
        post.author = user
        post.save()
        return redirect(f'/profile/{user}/')
    context = {
        'form': form,
        'is_edit': False
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect(f'/posts/{post_id}/')
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    if post.author != request.user:
        return redirect(f'/posts/{post_id}/')
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(f'/posts/{post_id}/')


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, N_EXEMPLE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'follow': True
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('/follow/')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('/follow/')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Создание нового поста{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать пост    
          {% else %}
            Новый пост
          {% endif %}              
        </div>
        <div class="card-body">
          {% load user_filters %}  
            {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
        {% csrf_token %}

        {% for field in form %}
          <div class="form-group row my-3"
            {% if field.field.required %} 
              aria-required="true"
            {% else %}
              aria-required="false"
            {% endif %}
          >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
          </div>
        {% endfor %}
        <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
            {% if is_edit %}
              Сохранить
            {% else %}
              Добавить
            {% endif %}               
          </button> 
        </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Записи избранных авторов{% endblock %}
{% block content %}
{% load thumbnail %}
{% load cache %}
  <h1>Записи избранных авторов</h1>
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
        <ul >
          <li>
            Автор: {{ post.author.get_full_name }} - {{ post.author.get_username }} 
            <span>(<a href="{% url 'space_posts:profile' post.author.get_username %}">посты пользователя</a>)</span>
          </li>
          <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "900x450" crop="top" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <p><a href="{{ post.get_absolute_url }}">подробная информация </a></p>
        {% if post.group is null %}
          <p> Нет группы </p>
        {% else %}       
            <a href="{% url 'space_posts:group_list' post.group.slug %}">все записи группы: {{ post.group }}</a>
        {% endif%}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }} - {{ post.author.get_username }}
          <span>(<a href="{% url 'space_posts:profile' post.author.get_username %}">посты пользователя</a>)</span>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "900x450" crop="top" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}
      </article> 
    {% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
{% load cache %}
{% cache 60 index_page page_obj.number %}
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
        <ul >
          <li>
            Автор: {{ post.author.get_full_name }} - {{ post.author.get_username }} 
            <span>(<a href="{% url 'space_posts:profile' post.author.get_username %}">посты пользователя</a>)</span>
          </li>
          <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "900x450" crop="top" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <p><a href="{{ post.get_absolute_url }}">подробная информация </a></p>
        {% if post.group is null %}
          <p> Нет группы </p>
        {% else %}       
            <a href="{% url 'space_posts:group_list' post.group.slug %}">все записи группы: {{ post.group }}</a>
        {% endif%}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endcache %}
{% include 'includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.text|truncatewords:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group is not null %}   
              <li class="list-group-item">
                Группа: {{ post.group }}
                <p><a href="{% url 'space_posts:group_list' post.group.slug %}">все записи группы</a></p>
              </li>
              {% endif%} 
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ number_posts }}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'space_posts:profile' post.author.get_username %}">все посты пользователя</a> 
            </li>
            {% if can_edit %}
              <li class="list-group-item">
                <a href="{% url 'space_posts:post_edit' post_id %}">редактировать пост</a> 
              </li>
            {% endif %}  
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "900x450" crop="top" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post"
                      action="{% url 'space_posts:add_comment' post.id %}">
                  {% csrf_token %}
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'space_posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                  <p>
                   {{ comment.text }}
                  </p>
                </div>
              </div>
          {% endfor %}
        </article>
      </div> 
    {% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }} ({{author}}){% endblock %}
{% block content %}
{% load thumbnail %}
    <div class="container py-5">
        <div class="mb-5">
            <h1>Все посты пользователя {{ author.get_full_name }}
                ({{ author }})</h1>
            <h3>Всего постов: {{ number_posts }}</h3>
            {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'space_posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
            {% else %}
                {% if not user_is_author %}
                  <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'space_posts:profile_follow' author.username %}" role="button"
                  >
                    Подписаться
                  </a>
                {% endif %}
           {% endif %}
        </div>
        {% for post in page_obj %}
            <article>
                <ul>
                <li>
                    Автор: {{ author.get_full_name }} ({{ author }})
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                </ul>
                {% thumbnail post.image "900x450" crop="top" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>{{ post.text }}</p>
                <a href="{{ post.get_absolute_url }}">подробная информация</a>
            </article> 
            {% if post.group is null %}
                <p> Нет группы </p>
            {% else %}
                 <a href="{% url 'space_posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }}</a>
            {% endif%}   
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        <hr> 
    </div>
{% include 'includes/paginator.html' %}
{% endblock %} 